### ISSUE TITLE
Android Basics: Persist data with Room | App crashes on item deletion

### ISSUE THREAD

**Issue by xmakina** [google-developer-training/android-basics-kotlin-inventory-app#23]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-update-data-room?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-5-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-update-data-room#4

**In which task and step of the codelab can this issue be found?**
Delete item entity, step 5

**Describe the problem**
On deleting the item, the app crashes and quits immediately.

**Steps to reproduce?**
1. Follow the tutorial as specified
2. Delete an item

**Versions**
_Android Studio version:_ 2020.3.1 Patch 3
_API version of the emulator:_ 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

Error message:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.inventory, PID: 10253
    java.lang.NullPointerException: selectedItem must not be null
        at com.example.inventory.ItemDetailFragment.onViewCreated$lambda-5(ItemDetailFragment.kt:103)
        ...
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process: Sending signal. PID: 10253 SIG: 9
```

Offending code:
![image](https://user-images.githubusercontent.com/1357791/144451894-0ddf1ece-d335-4deb-950a-93d5cde0b596.png)

The code matches what was provided in [step 4](https://developer.android.com/codelabs/basic-android-kotlin-training-update-data-room?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-5-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-update-data-room#3) Bind data to the TextViews step 9

**Comment by xmakina** [comment]
My bad, ensuring the showConfirmationDialog is called stops this error happening
